// Copyright (c) 2013-2015 Vittorio Romeo
// License: Academic Free License ("AFL") v. 3.0
// AFL License page: https://opensource.org/licenses/AFL-3.0

/*
Copyright (c) 2010, Pierre KRIEGER
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Check out Pierre Krieger's new version of luawrapper here:
// https://github.com/Tomaka17/luawrapper

#pragma once

#include "SSVOpenHexagon/Global/Assert.hpp"

#include "SFML/Base/Macros.hpp"
#include "SFML/Base/PlacementNew.hpp"
#include "SFML/Base/String.hpp"
#include "SFML/Base/StringView.hpp"
#include "SFML/Base/Trait/Decay.hpp"
#include "SFML/Base/Trait/IsFloatingPoint.hpp"
#include "SFML/Base/Trait/IsIntegral.hpp"
#include "SFML/Base/Trait/IsSame.hpp"
#include "SFML/Base/Trait/IsVoid.hpp"

#include <typeinfo>

#ifdef __CLANGD__
    #include <lauxlib.h>
    #include <lua.h>
#endif

#include <lua.hpp>
#include <tuple>

namespace Lua
{

template <typename>
struct RemoveMemberPtr;

template <typename TReturn, typename TThis, typename... TArgs>
struct RemoveMemberPtr<TReturn (TThis::*)(TArgs...) const>
{
    using Type = TReturn(TArgs...);
};


template <typename FnType>
struct FnTupleWrapper
{
};

template <typename... TArgs>
struct FnTupleWrapper<void(TArgs...)>
{
    enum
    {
        count = sizeof...(TArgs)
    };

    using ParamsType = std::tuple<TArgs...>;

    template <typename T>
    [[nodiscard, gnu::always_inline]] static inline constexpr std::tuple<> call(T&& fn, ParamsType&& mTpl)
    {
        std::apply(SFML_BASE_FORWARD(fn), SFML_BASE_MOVE(mTpl));
        return {};
    }
};

template <typename R, typename... TArgs>
struct FnTupleWrapper<R(TArgs...)>
{
    enum
    {
        count = sizeof...(TArgs)
    };

    using ParamsType = std::tuple<TArgs...>;

    template <typename T>
    [[nodiscard, gnu::always_inline]] static inline constexpr std::tuple<R> call(T&& fn, ParamsType&& mTpl)
    {
        return std::tuple<R>{std::apply(SFML_BASE_FORWARD(fn), SFML_BASE_MOVE(mTpl))};
    }
};

/**
 * @brief Defines a Lua context
 *
 * A Lua context is used to interpret Lua code. Since everything in Lua is a
 * variable (including functions),
 * we only provide few functions like readVariable and writeVariable. Note
 * that these functions can visit arrays,
 * ie. calling readVariable("a.b.c") will read variable "c" from array "b",
 * which is itself located in array "a".
 * You can also write variables with C++ functions so that they are callable
 * by Lua. Note however that you HAVE TO convert
 * your function to std::function (not directly std::bind or a lambda
 * function) so the class can detect which argument types
 * it wants. These arguments may only be of basic types (int, float, etc.)
 * or sf::base::String.
 */
class LuaContext
{
public:
    explicit LuaContext(bool openDefaultLibs = true);

    LuaContext(const LuaContext&)            = delete;
    LuaContext& operator=(const LuaContext&) = delete;

    LuaContext(LuaContext&& s) noexcept;
    LuaContext& operator=(LuaContext&& s) noexcept;

    ~LuaContext();


    /// \brief Thrown when an error happens during execution (like not
    /// enough parameters for a function)
    struct ExecutionErrorException;

    /// \brief Generated by readVariable or isVariableArray when the asked
    /// variable doesn't exist/is nil
    struct VariableDoesntExistException;

    /// \brief Thrown when a syntax error happens in a lua script
    struct SyntaxErrorException;

    /// \brief Thrown when trying to cast a lua variable to an invalid type
    struct WrongTypeException;

    [[noreturn]] static void _throwExecutionError(const sf::base::String& msg);
    [[noreturn]] static void _throwVariableDoesntExist(const sf::base::String& variable);
    [[noreturn]] static void _throwSyntaxError(const sf::base::String& msg);
    [[noreturn]] static void _throwWrongType();
    [[noreturn]] static void _throwBadAlloc();
    [[noreturn]] static void _throwUnknownRc(const sf::base::String& errorMsg);

    /// \brief Executes lua code given as parameter \param code A string
    /// containing code that will be executed by lua
    [[gnu::always_inline]] inline void executeCode(sf::base::StringView code)
    {
        _load(code);
        _call<std::tuple<>>(std::tuple<>());
    }

    /// \brief Executes lua code from the stream and returns a value \param
    /// code A stream that lua will read its code from
    template <typename T>
    [[nodiscard, gnu::always_inline]] inline T executeCode(sf::base::StringView code)
    {
        _load(code);
        return _call<T>(std::tuple<>());
    }

    /// \brief Calls a function stored in a lua variable
    /// \details Template parameter of the function should be the expected
    /// return type (tuples and void are supported)
    /// \param mVarName Name of the variable containing the function to call
    /// \param ... Parameters to pass to the function
    template <typename R, typename... Args>
    [[nodiscard, gnu::always_inline]] inline R callLuaFunction(sf::base::StringView mVarName, Args&&... args)
    {
        _getGlobal(mVarName);
        return _call<R>(std::make_tuple(SFML_BASE_FORWARD(args)...));
    }

    /// \brief Returns true if the value of the variable is an array \param
    /// mVarName Name of the variable to check
    [[nodiscard, gnu::always_inline]] inline bool isVariableArray(sf::base::StringView mVarName) const
    {
        _getGlobal(mVarName);

        const bool answer = lua_istable(_state, -1);
        lua_pop(_state, 1);
        return answer;
    }

    /// \brief Writes an empty array into the given variable \note To write
    /// something in the array, use writeVariable. Example:
    /// writeArrayIntoVariable("myArr"); writeVariable("myArr.something",
    /// 5);
    [[gnu::always_inline]] inline void writeArrayIntoVariable(sf::base::StringView mVarName)
    {
        lua_newtable(_state);
        _setGlobal(mVarName);
    }

    /// \brief Returns true if variable exists (ie. not nil)
    [[nodiscard, gnu::always_inline]] inline bool doesVariableExist(sf::base::StringView mVarName) const
    {
        _getGlobal(mVarName);

        const bool answer = lua_isnil(_state, -1);
        lua_pop(_state, 1);
        return !answer;
    }

    /// \brief Destroys a variable \details Puts the nil value into it
    [[gnu::always_inline]] inline void clearVariable(sf::base::StringView mVarName)
    {
        lua_pushnil(_state);
        _setGlobal(mVarName);
    }

    /// \brief Returns the content of a variable \throw
    /// VariableDoesntExistException if variable doesn't exist \note If you
    /// wrote a ObjectWrapper<T> into a variable, you can only read its
    /// value using a std::shared_ptr<T>
    template <typename T>
    [[nodiscard, gnu::always_inline]] inline T readVariable(sf::base::StringView mVarName) const
    {
        _getGlobal(mVarName);
        return _readTopAndPop(1, (T*)nullptr);
    }

    /// \brief
    template <typename T>
    [[nodiscard, gnu::always_inline]] inline bool readVariableIfExists(sf::base::StringView mVarName, T& out)
    {
        if (!doesVariableExist(mVarName))
        {
            return false;
        }

        out = readVariable<T>(mVarName);
        return true;
    }

    /// \brief Changes the content of a global lua variable
    /// \details Accepted values are: all base types (integers, floats),
    /// sf::base::String, std::function or ObjectWrapper<...>. All objects are
    /// passed by copy and destroyed by the garbage collector.
    template <typename T>
    void writeVariable(sf::base::StringView mVarName, T&& data)
    {
        static_assert(!SFML_BASE_IS_SAME(std::tuple<T>, T),
                      "Error: you can't use LuaContext::writeVariable with a tuple");

        const int pushedElems = _push(SFML_BASE_FORWARD(data));

        try
        {
            _setGlobal(mVarName);
        } catch (...)
        {
            lua_pop(_state, pushedElems - 1);
            throw;
        }

        lua_pop(_state, pushedElems - 1);
    }

private:
    // the state is the most important variable in the class since it is our
    // interface with Lua
    // the mutex is here because the lua design is not thread safe (based on
    // a stack)
    //   eg. if multiple thread call "writeVariable" at the same time, we
    //   don't want them to be executed simultaneously
    // the mutex should be locked by all public functions that use the stack
    lua_State* _state;

    // all the user types in the _state must have the value of &typeid(T) in
    // their
    //   metatable at key "_typeid"

    // the getGlobal function is equivalent to lua_getglobal, except that it
    // can interpret
    //   any variable name in a table form (ie. names like table.value are
    //   supported)
    // see also https://www.lua.org/manual/5.1/manual.html#lua_getglobal
    // same for setGlobal <=> lua_setglobal
    // important: _setGlobal will pop the value even if it throws an
    // exception, while _getGlobal won't push the value if it throws an
    // exception
    void _getGlobal(sf::base::StringView mVarName) const;
    void _setGlobal(sf::base::StringView mVarName);

    // simple function that reads the top # elements of the stack, pops
    // them, and returns them
    // warning: first parameter is the number of parameters, not the
    // parameter index
    // if _read generates an exception, stack is popped anyway
    template <typename R>
    [[gnu::always_inline]] inline R _readTopAndPop(int nb, R* ptr = nullptr) const
        requires(!sf::base::isVoid<R>)
    {
        try
        {
            R value = _read(-nb, ptr);
            lua_pop(_state, nb);
            return value;
        } catch (...)
        {
            lua_pop(_state, nb);
            throw;
        }
    }

    [[gnu::always_inline]] inline void _readTopAndPop(int nb, void*) const
    {
        lua_pop(_state, nb);
    }

    /**************************************************/
    /*              LOADING AND CALLING               */
    /**************************************************/
    // this function loads data from the stream and pushes a function at the
    // top of the stack
    // it is defined in the .cpp
    void _load(sf::base::StringView code);

    // this function calls what is on the top of the stack and removes it
    // (just like lua_call)
    // if an exception is triggered, the top of the stack will be removed
    // anyway
    // In should be a tuple (at least until variadic templates are supported
    // everywhere), Out can be anything
    template <typename Out, typename In>
    Out _call(const In& in)
    {
        static_assert(std::tuple_size_v<In> >= 0, "Error: template parameter 'In' should be a tuple");

        int outArguments{0};
        int inArguments{0};

        try
        {
            // we push the parameters on the stack
            outArguments = std::tuple_size_v<std::tuple<Out>>;
            inArguments  = _push(in);
        } catch (...)
        {
            lua_pop(_state, 1);
            throw;
        }

        // calling pcall automatically pops the parameters and pushes output
        const int pcallReturnValue = lua_pcall(_state, inArguments, outArguments, 0);

        // if pcall failed, analyzing the problem and throwing
        if (pcallReturnValue != 0)
        {
            // an error occurred during execution, an error message was
            // pushed on the stack
            const sf::base::String errorMsg = _readTopAndPop(1, (sf::base::String*)nullptr);

            if (pcallReturnValue == LUA_ERRMEM)
            {
                _throwBadAlloc();
            }
            else if (pcallReturnValue == LUA_ERRRUN)
            {
                _throwExecutionError(errorMsg);
            }
            else
            {
                _throwUnknownRc(errorMsg);
            }
        }

        // pcall succeeded, we pop the returned values and return them
        try
        {
            return _readTopAndPop(outArguments, (Out*)nullptr);
        } catch (...)
        {
            lua_pop(_state, outArguments);
            throw;
        }
    }


    /**************************************************/
    /*                PUSH FUNCTIONS                  */
    /**************************************************/

    // first the basic ones: integer, number, boolean, string
    [[gnu::always_inline]] inline int _push()
    {
        return 0;
    }

    [[gnu::always_inline]] inline int _push(bool v)
    {
        lua_pushboolean(_state, v);
        return 1;
    }

    [[gnu::always_inline]] inline int _push(sf::base::StringView s)
    {
        lua_pushstring(_state, s.data());
        return 1;
    }

    [[gnu::always_inline]] inline int _push(const char* s)
    {
        lua_pushstring(_state, s);
        return 1;
    }

    [[gnu::always_inline]] inline int _push(const sf::base::String& s)
    {
        lua_pushstring(_state, s.cStr());
        return 1;
    }

    // pushing floating numbers
    template <typename T>
    [[gnu::always_inline]] inline int _push(T nb)
        requires sf::base::isFloatingPoint<T>
    {
        lua_pushnumber(_state, nb);
        return 1;
    }

    // pushing integers
    template <typename T>
    [[gnu::always_inline]] inline int _push(T nb)
        requires sf::base::isIntegral<T>
    {
        lua_pushinteger(_state, nb);
        return 1;
    }

    // using variadic templates, you can push multiple values at once
    template <typename... Ts>
        requires(sizeof...(Ts) > 1)
    [[gnu::always_inline]] inline int _push(Ts&&... xs)
    {
        int p = 0;

        try
        {
            ((p += _push(SFML_BASE_FORWARD(xs))), ...);
        } catch (...)
        {
            lua_pop(_state, p);
            throw;
        }

        return p;
    }

    static void* callbackCallImpl(lua_State* lua);

    template <typename FunctionPushType>
    static auto callbackCall(lua_State* lua)
    {
        return (*(static_cast<FunctionPushType*>(callbackCallImpl(lua))))(lua);
    }

    template <typename FunctionPushType>
    static int callbackGarbage(lua_State* lua)
    {
        // this one is called when lua's garbage collector no longer
        // needs our custom data type
        // we call std::function<int (lua_State*)>'s destructor
        SSVOH_ASSERT(lua_gettop(lua) == 1);

        auto function = (FunctionPushType*)lua_touserdata(lua, 1);

        SSVOH_ASSERT(function);
        function->~FunctionPushType();

        return 0;
    }

    template <typename F, typename Op>
    struct FunctionToPush
    {
        LuaContext* _ctx;
        F           _fn;

        auto operator()(lua_State* state) const
        {
            SSVOH_ASSERT(_ctx->_state == state);

            // FnTupleWrapper<FnType> is a specialized template
            // structure which defines
            // "ParamsType", "ReturnType" and "call"
            // the first two correspond to the params list and return
            // type as tuples
            //   and "call" is a static function which will call a
            //   function
            //   of this type using parameters passed as a tuple
            using FnType         = typename RemoveMemberPtr<Op>::Type;
            using TupledFunction = FnTupleWrapper<FnType>;

            // checking if number of parameters is correct
            if (lua_gettop(state) < TupledFunction::count)
            {
                // if not, using lua_error to return an error
                luaL_where(state, 1);
                lua_pushstring(state, "this function requires at least ");
                lua_pushnumber(state, TupledFunction::count);
                lua_pushstring(state, " parameter(s)");
                lua_concat(state, 4);
                return lua_error(state); // lua_error throws an
                                         // exception when compiling as
                                         // C++
            }

            // pushing the result on the stack and returning number of
            // pushed elements
            return _ctx->_push(
                // calling the function, result should be a tuple
                TupledFunction::call(_fn,

                                     // reading parameters from the stack
                                     _ctx->_read(-TupledFunction::count,
                                                 static_cast<typename TupledFunction::ParamsType*>(nullptr))));
        }
    };

    void _pushFnImpl(int (*xCallbackCall)(lua_State*), int (*callbackGarbage)(lua_State*), const std::type_info& tiObject);

    // when you call _push with a functor, this definition should be used
    // (thanks to SFINAE)
    // it will determine the function category using its () operator, then
    //   generate a callable user data and push it
    template <typename T, typename DecayT = sf::base::Decay<T>, typename Op = decltype(&DecayT::operator())>
    int _push(T&& fn, Op = nullptr)
    {
        // when the lua script calls the thing we will push on the stack, we
        // want "fn" to be executed
        // if we used lua's cfunctions system, we could not detect when the
        // function is no longer in use, which could cause problems
        // so we use userdata instead

        // typedefing the type of data we will push
        using FunctionPushType = FunctionToPush<DecayT, Op>;

        // creating the object
        // lua_newuserdata allocates memory in the internals of the lua
        // library and returns it so we can fill it
        //   and that's what we do with placement-new
        auto* const functionLocation = (FunctionPushType*)lua_newuserdata(_state, sizeof(FunctionPushType));

        SFML_BASE_PLACEMENT_NEW(functionLocation) FunctionPushType{._ctx = this, ._fn = SFML_BASE_FORWARD(fn)};

        _pushFnImpl(&callbackCall<FunctionPushType>, &callbackGarbage<FunctionPushType>, typeid(T));

        return 1;
    }

    // pushing tuples is also possible, though a bit complicated
    template <typename... Args>
    [[gnu::always_inline]] inline int _push(const std::tuple<Args...>& t)
    {
        return [this, &t]<int... Is>(std::integer_sequence<int, Is...>)
        { return (this->_push(std::get<Is>(t)) + ... + 0); }(std::make_integer_sequence<int, sizeof...(Args)>{});
    }

    /**************************************************/
    /*                READ FUNCTIONS                  */
    /**************************************************/
    // to use the _read function, pass as second parameter a null pointer
    // whose base type is the wanted return type
    // eg. if you want an int, pass "static_cast<int*>(nullptr)" as second
    // parameter

    // reading void
    [[gnu::always_inline]] inline void _read(int, const void* = nullptr) const
    {
    }

    // first the integer types
    template <typename T>
    [[gnu::always_inline]] inline T _read(const int index, const T* = nullptr) const
        requires sf::base::isIntegral<T>
    {
        if (lua_isuserdata(_state, index))
        {
            _throwWrongType();
        }

        return T(lua_tointeger(_state, index));
    }

    // then the floating types
    template <typename T>
    [[gnu::always_inline]] inline T _read(const int index, const T* = nullptr) const
        requires sf::base::isFloatingPoint<T>
    {
        if (lua_isuserdata(_state, index))
        {
            _throwWrongType();
        }

        return T(lua_tonumber(_state, index));
    }

    // boolean
    [[gnu::always_inline]] inline bool _read(const int index, const bool* = nullptr) const
    {
        if (lua_isuserdata(_state, index))
        {
            _throwWrongType();
        }

        return lua_toboolean(_state, index) != 0; // "!= 0" removes a
                                                  // warning because
                                                  // lua_toboolean returns
                                                  // an int
    }

    // string
    // lua_tostring returns a temporary pointer, but that's not a problem
    // since we copy
    //   the data in a sf::base::String
    [[gnu::always_inline]] inline sf::base::String _read(const int index, const sf::base::String* = nullptr) const
    {
        if (lua_isuserdata(_state, index))
        {
            _throwWrongType();
        }

        return lua_tostring(_state, index);
    }

    template <typename... Ts>
    [[gnu::always_inline]] inline auto _read(const int index, const std::tuple<Ts...>* = nullptr)
    {
        return [this, index]<int... Is>(std::integer_sequence<int, Is...>)
        {
            return std::make_tuple(this->_read(index + Is, static_cast<sf::base::Decay<Ts>*>(nullptr))...);
        }(std::make_integer_sequence<int, sizeof...(Ts)>{});
    }

    [[gnu::always_inline]] inline constexpr std::tuple<> _read(int, const std::tuple<>* = nullptr) const noexcept
    {
        return {};
    }
};

} // namespace Lua
