#!/bin/bash

rm -Rf ./syslibs
mkdir -p ./syslibs
cp /usr/lib/libopenal.so.1 ./syslibs
cp /usr/lib/libvorbisenc.so.2 ./syslibs
cp /usr/lib/libvorbisfile.so.3 ./syslibs
cp /usr/lib/libvorbis.so.0 ./syslibs
cp /usr/lib/libogg.so.0 ./syslibs
cp /usr/lib/libFLAC.so.12 ./syslibs
cp /usr/lib/libdl.so.2 ./syslibs
cp /usr/lib/libXcursor.so.1 ./syslibs
cp /usr/lib/libXrandr.so.2 ./syslibs
cp /usr/lib/libXext.so.6 ./syslibs
cp /usr/lib/libXrender.so.1 ./syslibs
cp /usr/lib/libXfixes.so.3 ./syslibs
cp /usr/lib/libX11.so.6 ./syslibs
cp /usr/lib/libudev.so.1 ./syslibs
cp /usr/lib/libfreetype.so.6 ./syslibs
cp /usr/lib/libGL.so.1 ./syslibs
cp /usr/lib/libGLU.so.1 ./syslibs
cp /usr/lib/libstdc++.so.6 ./syslibs
cp /usr/lib/libm.so.6 ./syslibs
cp /usr/lib/libgcc_s.so.1 ./syslibs
cp /usr/lib/libc.so.6 ./syslibs
cp /usr/lib64/ld-linux-x86-64.so.2 ./syslibs
cp /usr/lib/libpthread.so.0 ./syslibs
cp /usr/lib/librt.so.1 ./syslibs
cp /usr/lib/libxcb.so.1 ./syslibs
cp /usr/lib/libcap.so.2 ./syslibs
cp /usr/lib/libbz2.so.1.0 ./syslibs
cp /usr/lib/libpng16.so.16 ./syslibs
cp /usr/lib/libharfbuzz.so.0 ./syslibs
cp /usr/lib/libbrotlidec.so.1 ./syslibs
cp /usr/lib/libGLdispatch.so.0 ./syslibs
cp /usr/lib/libGLX.so.0 ./syslibs
cp /usr/lib/libOpenGL.so.0 ./syslibs
cp /usr/lib/libXau.so.6 ./syslibs
cp /usr/lib/libXdmcp.so.6 ./syslibs
cp /usr/lib/libglib-2.0.so.0 ./syslibs
cp /usr/lib/libgraphite2.so.3 ./syslibs
cp /usr/lib/libbrotlicommon.so.1 ./syslibs
cp /usr/lib/libpcre2-8.so.0 ./syslibs
