# -*- cmake -*-

# - Find SSVUtils
# Find the SSVUtils includes and library
# This module defines
# SSVUTILS_INCLUDE_DIR, where to find SSVUtils headers.
# SSVUTILS_LIBRARIES, the libraries needed to use SSVUtils.
# SSVUTILS_FOUND, If false, do not try to use SSVUtils.
# also defined, but not for general use are
# SSVUTILS_LIBRARY, where to find the SSVUtils library.

FIND_PATH(SSVMENUSYSTEM_INCLUDE_DIR
  NAMES SSVMenuSystem/SSVMenuSystem.h
  PATH_SUFFIXES include
  PATHS "/usr/local/"
)


FIND_LIBRARY(SSVMENUSYSTEM_LIBRARY
  NAMES SSVMenuSystem libSSVMenuSystem SSVMenuSystem-s libSSVMenuSystem-s ssvmenusystem libssvmenusystem ssvmenusystem-s libssvmenusystem-s
  PATH_SUFFIXES lib/ lib64/
  PATHS /usr/ /usr/local/
)

IF (SSVMENUSYSTEM_LIBRARY AND SSVMENUSYSTEM_INCLUDE_DIR)
    SET(SSVMENUSYSTEM_LIBRARIES ${SSVMENUSYSTEM_LIBRARY})
    SET(SSVMENUSYSTEM_FOUND TRUE)
ELSE (SSVMENUSYSTEM_LIBRARY AND SSVMENUSYSTEM_INCLUDE_DIR)
    SET(SSVMENUSYSTEM_FOUND FALSE)
ENDIF (SSVMENUSYSTEM_LIBRARY AND SSVMENUSYSTEM_INCLUDE_DIR)


IF (SSVMENUSYSTEM_FOUND)
   #IF (NOT SSVMENUSYSTEM_FIND_QUIETLY)
      MESSAGE(STATUS "Found SSVMenuSystem in ${SSVMENUSYSTEM_INCLUDE_DIR}")
   #ENDIF (NOT SSVMENUSYSTEM_FIND_QUIETLY)
ELSE (SSVMENUSYSTEM_FOUND)
   IF (SSVMENUSYSTEM_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find SSVMenuSystem library")
   ENDIF (SSVMENUSYSTEM_FIND_REQUIRED)
ENDIF (SSVMENUSYSTEM_FOUND)

MARK_AS_ADVANCED(
  SSVMENUSYSTEM_LIBRARY
  SSVMENUSYSTEM_INCLUDE_DIR
)
