FIND_PATH(SPARSEHASH_INCLUDE_DIR
  NAMES google/dense_hash_map
  PATH_SUFFIXES include/ google/ google/sparsehash/ 
  PATHS "${PROJECT_SOURCE_DIR}/../sparsehash/"
  "${PROJECT_SOURCE_DIR}/extlibs/sparsehash/"
  ${SPARSEHASH_ROOT}
  $ENV{SPARSEHASH_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound Sparsehash include at: ${SPARSEHASH_INCLUDE_DIR}.\n")

IF(SPARSEHASH_INCLUDE_DIR)
  SET(SPARSEHASH_FOUND TRUE)
ELSE(SPARSEHASH_INCLUDE_DIR)
  SET(SPARSEHASH_FOUND FALSE)
ENDIF(SPARSEHASH_INCLUDE_DIR)

IF(SPARSEHASH_FOUND)
  MESSAGE(STATUS "Found SPARSEHASH in ${SPARSEHASH_INCLUDE_DIR}")
ELSE(SPARSEHASH_FOUND)
  IF(SPARSEHASH_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SPARSEHASH library")
  ENDIF(SPARSEHASH_FIND_REQUIRED)
ENDIF(SPARSEHASH_FOUND)

MARK_AS_ADVANCED(
  SPARSEHASH_INCLUDE_DIR
)
